### PR TITLE
Fix #2 - Fix default return value

### LINKED ISSUE #2: How to set default value to false?
Hi,

I'm trying to use `prompt-confirm` to ask the user a question, but the prompts defaults to `(Y/n)` and when simply pressing `<Enter>` the answer is set to `true`.

By using `{default: false}` (hinted by [this](https://github.com/enquirer/prompt-confirm/blob/master/index.js#L20)) I managed to make the prompt defaults to `(y/N)`, but even so, just pressing `<Enter>` without writing anything sets the answer to `false`.

Basic example below:

``` Javascript
'use strict';

const inspect  = require ('util').inspect
const Enquirer = require ('enquirer')

let enquirer = new Enquirer ()
enquirer.register ('confirm', require ('prompt-confirm'))

enquirer.question ('agree', 'Do you agree?', {
    type: 'confirm',
    default: false
})

enquirer.ask()
.then( answer => {
    console.log ('Answer: ' + inspect (answer, {colors: true}))
})
```

And the console session that goes with it:

``` Bash
? Do you agree? (y/N) #Pressing <Enter>

? Do you agree? true
Answer: { agree: true }
```

(Note that I displayed the the question twice simply to show that the prompt indeeds switches to `(y/N)`, but there are no display problem, it doesn't actually get repeated).

As you see, simply pressing enter sets the answer to `false`.

I tried setting `defaultValue: false` as well in the parameters, but it doesn't work.

### PR DESCRIPTION
**Pull request by nschoe**
So what I did :
- the `var defaultValue` was changed to `this.defaultValue` so that it can be access. I just need confirmation that it makes sense and won't screw up: should I keep it like this **or** should I turn it into `this.question.defaultValue`. It might make more sense?
- I change the `isString()` function so that it checks for the type of the parameters and that it's not empty
- I remove the double negation `!!` in `getAnswer()` since it's not needed anymore (`isString()` now returns a boolean).

Seems good to you?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Great thank you! I'll try to merge ASAP. I'll do my best to do this today (or maybe @doowb can take a look if he has a moment).

**Comment by doowb** [comment]
This looks good at first glance. I'll pull it down in a little bit and check it out. Thanks @nschoe  for digging into the code and making the changes.

**Comment by nschoe** [comment]
Okay no prob. I'm not too used to automated testing: why is there a failing check?

**Comment by doowb** [comment]
@nschoe thanks for the changes. I checked them out and played around with the examples a little to make sure they worked as expected.

We're still working on figuring out the best way to test these prompts through unit tests, but those aren't in place yet, so the continuous integration services are currently failing. Thanks for working through these bugs with us since this code is fairly new.

**Comment by nschoe** [comment]
Okay, glad I could help =)

**Pull request merged**
